### ISSUE TITLE
Readme wrong?

### ISSUE THREAD

**Issue by Carter4242** [MoralCode/pawprints-notify#3]
I don't think the readme is talking about the right project.

**Comment by MoralCode** [comment]
yeah thats correct - this was pretty much forked from another repo of mine because i had made a discord bot to notify me of things for another project (https://classclock.app) and didnt want to re-invent that wheel

**Comment by MoralCode** [comment]
fixed in bca8228ee0b75df4867b412d18bbf6eb069d727b
